# Gradle Settings
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

# Maven Metadata
archives_base_name=example-mod
maven_group=io.github.blockneko11

# Mod Metadata
mod_id=example_mod
mod_version=1.0.0
mod_name=Example Mod
mod_description=Example Mod
mod_home_page=https://github.com/example
mod_sources_page=https://github.com/example/example-mod

# Minecraft Settings
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_mcver_dependency=>=1.21 <1.21.2
fabric_loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1

# FML
fml_mcver_dependency=[1.21, 1.21.2)

# Forge
# forge_version=47.4.3-1.20.1
# forge_dependency=[46, )

# NeoForge
neoforge_version=21.1.233
neoforge_dependency=[21.0, 21.2)

# Mixin Extras
# mixinextras_version=0.4.1

# Mod dependencies
# Architectury Api
# architectury_version=9.2.14
